import type { Character } from './types'

export const CHARACTERS: Character[] = [
  { id: 'zeta',         name: 'Zeta',         tag: 'ZET', archetypes: ["all-rounder"] },
  { id: 'vaseraga',     name: 'Vaseraga',     tag: 'VAS', archetypes: ['grappler'] },
  { id: 'beatrix',      name: 'Beatrix',      tag: 'BEA', archetypes: ['all-rounder', "rushdown"] },
  { id: 'eustace',      name: 'Eustace',      tag: 'EUS', archetypes: ['zoner', "setplay"] },
  { id: 'anre',         name: 'Anre',         tag: 'ANR', archetypes: ['zoner', "technical"] },
  { id: 'seox',         name: 'Seox',         tag: 'SEO', archetypes: ['rushdown'] },
  { id: 'lancelot',     name: 'Lancelot',     tag: 'LAN', archetypes: ['rushdown'] },
  { id: 'vane',         name: 'Vane',         tag: 'VAN', archetypes: ['zoner'] },
  { id: 'percival',     name: 'Percival',     tag: 'PER', archetypes: ['all-rounder', "technical"] },
  { id: 'siegfried',    name: 'Siegfried',    tag: 'SIE', archetypes: ['all-rounder'] },
  { id: 'versusia',     name: 'Versusia',     tag: 'VRS', archetypes: ['zoner'] },
  { id: 'zooey',        name: 'Zooey',        tag: 'ZOO', archetypes: ['all-rounder'] },
  { id: 'ladiva',       name: 'Ladiva',       tag: 'LAD', archetypes: ['grappler'] },
  { id: 'narmaya',      name: 'Narmaya',      tag: 'NAR', archetypes: ['technical', "all-rounder"] },
  { id: 'ex-narmaya',   name: 'Narmaya (EX)',   tag: 'NEX', archetypes: ['all-rounder'] },
  { id: 'gran',         name: 'Gran',         tag: 'GRN', archetypes: ['all-rounder'] },
  { id: 'ex-gran',      name: 'Gran (EX)',      tag: 'GEX', archetypes: ['rushdown', "all-rounder"] },
  { id: 'djeeta',       name: 'Djeeta',       tag: 'DJE', archetypes: ['all-rounder'] },
  { id: 'ex-djeeta',    name: 'Djeeta (EX)', tag: 'DEX', archetypes: ['rushdown'] },
  { id: 'charlotta',    name: 'Charlotta',    tag: 'CHA', archetypes: ['rushdown'] },
  { id: 'ferry',        name: 'Ferry',        tag: 'FER', archetypes: ['setplay', "zoner"] },
  { id: 'anila',        name: 'Anila',        tag: 'ANI', archetypes: ['all-rounder'] },
  { id: 'vikala',       name: 'Vikala',       tag: 'VIK', archetypes: ['zoner'] },
  { id: 'galleon',      name: 'Galleon',      tag: 'GAL', archetypes: ['grappler', 'setplay'] },
  { id: 'grimnir',      name: 'Grimnir',      tag: 'GRI', archetypes: ['setplay', 'rushdown', 'technical'] },
  { id: 'metera',       name: 'Metera',       tag: 'MET', archetypes: ['zoner', 'setplay'] },
  { id: 'lowain',       name: 'Lowain',       tag: 'LOW', archetypes: ["technical", 'setplay'] },
  { id: 'katalina',     name: 'Katalina',     tag: 'KAT', archetypes: ['all-rounder'] },
  { id: 'vira',         name: 'Vira',         tag: 'VIR', archetypes: ['rushdown'] },
  { id: 'yuel',         name: 'Yuel',         tag: 'YUE', archetypes: ['rushdown'] },
  { id: 'soriz',        name: 'Soriz',        tag: 'SOR', archetypes: ['rushdown'] },
  { id: 'cagliostro',   name: 'Cagliostro',   tag: 'CAG', archetypes: ['setplay', "technical"] },
  { id: 'wilnas',       name: 'Wilnas',       tag: 'WIL', archetypes: ['grappler'] },
  { id: 'ilsa',         name: 'Ilsa',         tag: 'ILS', archetypes: ['all-rounder'] },
  { id: 'sandalphon',   name: 'Sandalphon',   tag: 'SAN', archetypes: ['all-rounder'] },
  { id: 'nier',         name: 'Nier',         tag: 'NIE', archetypes: ['technical'] },
  { id: 'belial',       name: 'Belial',       tag: 'BLL', archetypes: ['all-rounder'] },
  { id: 'beelzebub',    name: 'Beelzebub',    tag: 'BEL', archetypes: ["all-rounder"] },
  { id: 'lucilius',     name: 'Lucilius',     tag: 'LUC', archetypes: ["zoner"] },
  { id: 'avatar-belial',name: 'Avatar Belial',tag: 'AVB', archetypes: ["technical"] },
  { id: '2b',           name: '2B',           tag: 'TWB', archetypes: ['technical'] },
  { id: 'meg',          name: 'Meg',          tag: 'MEG', archetypes: ['rushdown', "all-rounder"] }
]

export function getCharacterById(id: string): Character | undefined {
  return CHARACTERS.find(c => c.id === id)
}
