// This file will be generated by Wails
// Add type declarations for your Go methods here

import { Note, Config, UpdateInfo } from './types';

declare global {
  interface Window {
    go: {
      main: {
        App: {
          GetConfig(): Promise<Config>;
          
          // Note methods
          CreateNote(note: Note): Promise<void>;
          GetNoteByID(id: number): Promise<Note>;
          GetNotesByCharacter(characterName: string): Promise<Note[]>;
          UpdateNote(note: Note): Promise<void>;
          DeleteNote(id: number): Promise<void>;
          SearchNotes(characterName: string, query: string): Promise<Note[]>;
          
          // Setting methods
          GetSetting(key: string): Promise<string>;
          SetSetting(key: string, value: string): Promise<void>;
          GetExModeEnabled(): Promise<boolean>;
          SetExModeEnabled(enabled: boolean): Promise<void>;
          
          // Update methods
          CheckForUpdates(): Promise<UpdateInfo>;
          
          // Character data
          GetCharacterList(): Promise<string[]>;
          GetExCharacters(): Promise<string[]>;
        };
      };
    };
  }
}

export {};
