// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function CreateNote(arg1:models.Note):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function GetCharacterList():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetExCharacters():Promise<Array<string>>;

export function GetExModeEnabled():Promise<boolean>;

export function GetNoteByID(arg1:number):Promise<models.Note>;

export function GetNotesByCharacter(arg1:string):Promise<Array<models.Note>>;

export function GetSetting(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SearchNotes(arg1:string,arg2:string):Promise<Array<models.Note>>;

export function SetExModeEnabled(arg1:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateNote(arg1:models.Note):Promise<void>;
