// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetCharacterList() {
  return window['go']['main']['App']['GetCharacterList']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetExCharacters() {
  return window['go']['main']['App']['GetExCharacters']();
}

export function GetExModeEnabled() {
  return window['go']['main']['App']['GetExModeEnabled']();
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function GetNotesByCharacter(arg1) {
  return window['go']['main']['App']['GetNotesByCharacter'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchNotes(arg1, arg2) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2);
}

export function SetExModeEnabled(arg1) {
  return window['go']['main']['App']['SetExModeEnabled'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}
